[package]
name = "wasi_example"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[lib]
name = "wasi_example_lib"
path = "src/lib.rs"
crate-type =["cdylib"]

[dependencies]
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
getrandom = "0.1.14"
wasm-bindgen = "=0.2.61"
