name: Node.js examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install apt-get packages
      run: |
        sudo apt-get install build-essential curl wget git vim libboost-all-dev
    
    - name: Install npm packages
      run: |
        npm i ssvm sync-request better-sqlite3
        npm i -g ssvmup
        npm i -g wasm-pack
    
    - name: Functions
      run: |
        ssvmup build
        cp pkg/* node/
        node node/app.js
      working-directory: nodejs/functions
      
    - name: JSON IO
      run: |
        ssvmup build
        cp pkg/* node/
        node node/app.js
      working-directory: nodejs/json_io

    - name: Nodejs API
      run: |
        wasm-pack build --target nodejs
        cd node/
        node date.js
        node db.js
        node http.js
        node image.js
        node cleanup.js
      working-directory: nodejs/nodejs_example

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ubuntu-18.04-nodejs-${{ matrix.node-version }}
        path: nodejs
